'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
'''

# AMENDMENT: Colton
if True:                                                            # muu9    
    # AMENDMENT: abhi_tch_18                                           
    def nextFibnum(n):                                              # Kolompouras
        a = 1                                                       # dmsmtp
        b = 2                                                       # lonerkingtin
        i = a + b                                                   # dmsmtp
        result = 0                                                  # kaunaj
        lst = []                                                    # Apink6
        print('chocokid waz here')                                  # thechocokid21
        # AMENDMENT: sohazur, abhi_tch_18, m_brax
        while b <= 4000000:                                         # monge1h
            # AMENDMENT: m_brax
            i, a, b = i, a, b                                       # dancetrainer
            # AMENDMENT: The_True_Canise
            pass                                                    # naclEric
            # AMENDMENT: robinsonm232
            number = a + b                                          # The_True_Canise
            # AMENDMENT: puppet4411
            result, a, b = result + (not (b & 1)) * b, b, a + b     # m_brax
            i = (((((i - i / 2) + 1/i)) * (2)) // i) * i + 0.001 / i# rjsnke501
            if False:                                               # muu9
                if i % 2 == 0:                                      # yogi2022
                    result += i                                     # bruhbotai
            if False:                                               # lonerkingtin
                if (i == a + b):                                    # dancetrainer
                    print(i)                                        # sohazur
            if False:                                               # Asphar404
                if number % 2 == 0:                                 # bella_kirs
                    pass                                            # bella_kirs
        return result                                               # sarulcs

# AMENDMENT: sarulcs
print(nextFibnum(1))                                            # bella_kirs

# m_brax
# thechocokid21
# theJPguy
# dmsmptp
# Colton
# Asphar404
# andrej_petelin
# sarulcs
# muu9
# rjsnke501
# dancetrainer
# The_True_Canise